# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Verify code
run-name: Verify code in branch [${{ github.ref }}] by @${{ github.actor }}

on:
  pull_request:
    branches: [ "main", "dev"]
  push:
    branches:
      - "main"

jobs:
  build-and-verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17 âš™ï¸
      uses: "./.github/template/setup/java"
    - name: build ğŸ› ï¸
      uses: "./.github/template/build"
    - name: test ğŸ§ª
      uses: "./.github/template/test"

